CREATE SCHEMA IF NOT EXISTS account;

CREATE TABLE account.account
(
    id                     UUID         NOT NULL,
    username               VARCHAR(255) NOT NULL,
    password               VARCHAR(255) NOT NULL,
    is_enabled             BOOLEAN      NOT NULL,
    is_account_non_expired BOOLEAN      NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_login_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

CREATE TABLE account.account_authority
(
    account_id   UUID   NOT NULL,
    authority_id BIGINT NOT NULL,
    CONSTRAINT pk_account_authority PRIMARY KEY (account_id, authority_id)
);

CREATE TABLE account.authority
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_authority PRIMARY KEY (id)
);

ALTER TABLE account.account_authority
    ADD CONSTRAINT uc_account_authority_authority UNIQUE (authority_id);

ALTER TABLE account.account
    ADD CONSTRAINT uc_account_username UNIQUE (username);

ALTER TABLE account.authority
    ADD CONSTRAINT uc_authority_name UNIQUE (authority);

ALTER TABLE account.account_authority
    ADD CONSTRAINT fk_accaut_on_account_entity FOREIGN KEY (account_id) REFERENCES account.account (id);

ALTER TABLE account.account_authority
    ADD CONSTRAINT fk_accaut_on_authority_entity FOREIGN KEY (authority_id) REFERENCES account.authority (id);